spring:
  mail:
    host: smtp.qq.com
    username: ${Email:1711858319@qq.com}
    password: ${QQ_SMTP:ynpehhroknoebfhg}
    port: 465
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: false
        debug: false
        personal: ICE

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: email

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# JWT Token Expiration Configuration
auth:
  jwt-access-expiration: 120   # Access token expiration in minutes
  jwt-refresh-expiration: 7   # Refresh token expiration in days
