spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:10.0.0.2}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin@2026}

  data:
    redis:
      host: ${REDIS_HOST:10.0.0.2}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:10.0.0.2}:${MYSQL_PORT:3306}/chat_book_user?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}

oauth2:
  success:
    redirect-url: ${OAUTH2_SUCCESS_REDIRECT_URL:http://putl.online/login}
