spring:
  config:
    import: optional:nacos:article-service-${spring.profiles.active}.yml
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

file:
  storage:
    base-url: ${FILE_STORAGE_BASE_URL:}

websocket:
  path: /article/ws
